version: '3'

networks:
  laravel:

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: awahan_laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:10.5.8
    container_name: mysql
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_DATABASE: awahan
      MARIADB_USER: root
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
